version: '3.7'

services:
  auth-db:
    restart: unless-stopped
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: auth
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webnet
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: postgres
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "8080:80"
      networks:
        - webnet
      volumes:
        - pgadmin-data:/var/lib/pgadmin
      links:
        - "auth-db:auth-db"
networks:
  webnet:
volumes:
  pgdata:
  pgadmin-data:
